import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Lang = 'vi' | 'en';

const translations = {
  vi: {
    appName: 'EduQuiz',
    tagline: 'Tạo và chia sẻ bài kiểm tra thông minh với AI',
    home: 'Trang chủ',
    myQuizzes: 'Bộ quiz của tôi',
    library: 'Thư viện',
    settings: 'Cài đặt',
    login: 'Đăng nhập',
    register: 'Đăng ký',
    logout: 'Đăng xuất',
    createQuiz: 'Tạo Quiz',
    createManual: 'Tạo thủ công',
    createAI: 'Tạo bằng AI',
    editQuiz: 'Chỉnh sửa Quiz',
    deleteQuiz: 'Xóa',
    restoreQuiz: 'Khôi phục',
    publish: 'Công khai',
    unpublish: 'Riêng tư',
    startQuiz: 'Bắt đầu làm bài',
    submit: 'Nộp bài',
    score: 'Điểm số',
    leaderboard: 'Bảng xếp hạng',
    results: 'Kết quả',
    questions: 'câu hỏi',
    difficulty: 'Độ khó',
    easy: 'Dễ',
    medium: 'Trung bình',
    hard: 'Khó',
    topic: 'Chủ đề',
    title: 'Tiêu đề',
    description: 'Mô tả',
    author: 'Tác giả',
    email: 'Email',
    password: 'Mật khẩu',
    name: 'Họ tên',
    save: 'Lưu',
    cancel: 'Hủy',
    delete: 'Xóa',
    confirm: 'Xác nhận',
    loading: 'Đang tải...',
    error: 'Có lỗi xảy ra',
    success: 'Thành công',
    noQuizzes: 'Chưa có quiz nào',
    trash: 'Thùng rác',
    shareCode: 'Mã chia sẻ',
    copyCode: 'Sao chép mã',
    copied: 'Đã sao chép!',
    joinByCode: 'Tham gia bằng mã',
    enterCode: 'Nhập mã quiz...',
    join: 'Tham gia',
    profile: 'Hồ sơ',
    avatar: 'Ảnh đại diện',
    bio: 'Giới thiệu',
    changePassword: 'Đổi mật khẩu',
    currentPassword: 'Mật khẩu hiện tại',
    newPassword: 'Mật khẩu mới',
    confirmPassword: 'Xác nhận mật khẩu',
    addQuestion: 'Thêm câu hỏi',
    question: 'Câu hỏi',
    option: 'Đáp án',
    correctAnswer: 'Đáp án đúng',
    explanation: 'Giải thích',
    generateAI: 'Tạo bằng AI',
    generating: 'Đang tạo...',
    numQuestions: 'Số câu hỏi',
    yourAnswer: 'Câu trả lời của bạn',
    correct: 'Đúng',
    incorrect: 'Sai',
    enterName: 'Nhập tên của bạn',
    guestName: 'Tên người chơi',
    playAsGuest: 'Chơi không cần đăng nhập',
    rank: 'Hạng',
    you: 'Bạn',
    totalScore: 'Tổng điểm',
    retake: 'Làm lại',
    backHome: 'Về trang chủ',
    publicLibrary: 'Thư viện công khai',
    myProfile: 'Trang cá nhân',
    deleteAccount: 'Xóa tài khoản',
    forgotPassword: 'Quên mật khẩu?',
    sendReset: 'Gửi email đặt lại',
    resetPassword: 'Đặt mật khẩu mới',
    language: 'Ngôn ngữ',
    theme: 'Giao diện',
    light: 'Sáng',
    dark: 'Tối',
    system: 'Theo hệ thống',
    essayQuestion: 'Câu hỏi tự luận',
    sampleAnswer: 'Đáp án mẫu',
    aiGrading: 'AI đang chấm...',
    feedback: 'Nhận xét',
    playedTimes: 'lượt chơi',
    quizStats: 'Thống kê',
    notFound: 'Không tìm thấy',
    backToQuizzes: 'Về danh sách quiz',
    multipleChoice: 'Trắc nghiệm',
    trueFalse: 'Đúng/Sai',
    essay: 'Tự luận',
    imageUrl: 'URL hình ảnh',
    previewImage: 'Xem trước ảnh',
    noDescription: 'Không có mô tả',
    createdAt: 'Ngày tạo',
    by: 'bởi',
  },
  en: {
    appName: 'EduQuiz',
    tagline: 'Create and share smart quizzes with AI',
    home: 'Home',
    myQuizzes: 'My Quizzes',
    library: 'Library',
    settings: 'Settings',
    login: 'Login',
    register: 'Register',
    logout: 'Logout',
    createQuiz: 'Create Quiz',
    createManual: 'Create Manually',
    createAI: 'Create with AI',
    editQuiz: 'Edit Quiz',
    deleteQuiz: 'Delete',
    restoreQuiz: 'Restore',
    publish: 'Make Public',
    unpublish: 'Make Private',
    startQuiz: 'Start Quiz',
    submit: 'Submit',
    score: 'Score',
    leaderboard: 'Leaderboard',
    results: 'Results',
    questions: 'questions',
    difficulty: 'Difficulty',
    easy: 'Easy',
    medium: 'Medium',
    hard: 'Hard',
    topic: 'Topic',
    title: 'Title',
    description: 'Description',
    author: 'Author',
    email: 'Email',
    password: 'Password',
    name: 'Full Name',
    save: 'Save',
    cancel: 'Cancel',
    delete: 'Delete',
    confirm: 'Confirm',
    loading: 'Loading...',
    error: 'An error occurred',
    success: 'Success',
    noQuizzes: 'No quizzes yet',
    trash: 'Trash',
    shareCode: 'Share Code',
    copyCode: 'Copy Code',
    copied: 'Copied!',
    joinByCode: 'Join by Code',
    enterCode: 'Enter quiz code...',
    join: 'Join',
    profile: 'Profile',
    avatar: 'Avatar',
    bio: 'Bio',
    changePassword: 'Change Password',
    currentPassword: 'Current Password',
    newPassword: 'New Password',
    confirmPassword: 'Confirm Password',
    addQuestion: 'Add Question',
    question: 'Question',
    option: 'Option',
    correctAnswer: 'Correct Answer',
    explanation: 'Explanation',
    generateAI: 'Generate with AI',
    generating: 'Generating...',
    numQuestions: 'Number of Questions',
    yourAnswer: 'Your Answer',
    correct: 'Correct',
    incorrect: 'Incorrect',
    enterName: 'Enter your name',
    guestName: 'Player Name',
    playAsGuest: 'Play as Guest',
    rank: 'Rank',
    you: 'You',
    totalScore: 'Total Score',
    retake: 'Retake',
    backHome: 'Back to Home',
    publicLibrary: 'Public Library',
    myProfile: 'My Profile',
    deleteAccount: 'Delete Account',
    forgotPassword: 'Forgot Password?',
    sendReset: 'Send Reset Email',
    resetPassword: 'Reset Password',
    language: 'Language',
    theme: 'Theme',
    light: 'Light',
    dark: 'Dark',
    system: 'System',
    essayQuestion: 'Essay Question',
    sampleAnswer: 'Sample Answer',
    aiGrading: 'AI grading...',
    feedback: 'Feedback',
    playedTimes: 'plays',
    quizStats: 'Statistics',
    notFound: 'Not Found',
    backToQuizzes: 'Back to Quizzes',
    multipleChoice: 'Multiple Choice',
    trueFalse: 'True/False',
    essay: 'Essay',
    imageUrl: 'Image URL',
    previewImage: 'Preview Image',
    noDescription: 'No description',
    createdAt: 'Created',
    by: 'by',
  }
};

interface LangContextType {
  lang: Lang;
  setLang: (l: Lang) => void;
  t: typeof translations['vi'];
}

const LangContext = createContext<LangContextType | undefined>(undefined);

export const LangProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [lang, setLang] = useState<Lang>('vi');
  const t = translations[lang];
  return <LangContext.Provider value={{ lang, setLang, t }}>{children}</LangContext.Provider>;
};

export const useLang = () => {
  const ctx = useContext(LangContext);
  if (!ctx) throw new Error('useLang must be used within LangProvider');
  return ctx;
};
